version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: America/Sao_Paulo
  open-pull-requests-limit: 10
  commit-message:
    prefix: "build"
